CREATE TABLE IF NOT EXISTS pet_owner (
    petOwnerId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    firstName VARCHAR(30) NOT NULL,
    lastName VARCHAR(30) NOT NULL,
    fullName VARCHAR(30) NOT NULL,
    address TEXT,
    cNumber VARCHAR(30) NOT NULL,
    profilePicture VARCHAR(255) DEFAULT 'media/default-profile.png',
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) AUTO_INCREMENT = 10000000;
