CREATE TABLE IF NOT EXISTS pets (
    petId INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    petOwnerId INT(8) UNSIGNED NOT NULL,
    petName VARCHAR(30) NOT NULL,
    species VARCHAR(30) NOT NULL,
    breed VARCHAR(30) NOT NULL,
    birthDate DATE NOT NULL,
    sex VARCHAR(10) NOT NULL,   
    age INT NOT NULL,
    petImage_url TEXT,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) AUTO_INCREMENT = 50000000;    